export const demoAcademicSystem = {
  period: {
    id: "2026-1",
    studentRange: "Febrero 2026 – Noviembre 2027",
  },
  instructor: {
    id: "DEMO-INSTRUCTOR-LR",
    name: "Laura Romero",
    initials: "LR",
    title: "Profesora titular",
    email: "laura.romero@usal.es",
    phone: "300 555 0184",
    faculty: "Ciencias y Tecnología",
    specialty: "Tecnologías de la información",
  },
  student: {
    id: "student-001",
    name: "Daniel Felipe Rojas Gómez",
    shortName: "Daniel Rojas",
    initials: "DR",
    document: "1023456789",
    recordNumber: "2876543",
    email: "daniel.rojas@correo.edu.co",
    phone: "300 456 7890",
  },
  flagshipGroup: {
    id: "FIC-DEMO-2874901",
    number: "2874901",
    program: "Análisis y Desarrollo de Software",
    shortProgram: "ADSO",
    modality: "Presencial",
    shift: "Manana" as const,
    shiftLabel: "Mañana",
    schedule: "Lun a jue 07:00 - 11:00",
    site: "Chapinero",
    campus: "Campus Salamanca - Sede Principal",
    room: "Laboratorio B-204",
    studentCount: 32,
    state: "Confirmada" as const,
    note: "Cambio de aula confirmado, sin afectar la continuidad de la clase.",
  },
  flagshipSession: {
    id: "SESSION-DEMO-2874901-2026-08-24",
    date: "2026-08-24",
    dateLabel: "Lun 24",
    dayName: "Lunes",
    startTime: "07:00",
    endTime: "11:00",
    title: "Sesión ADSO",
  },
} as const;

export const demoAcademicWeek = [
  { name: "Lunes", shortName: "Lun", date: "24" },
  { name: "Martes", shortName: "Mar", date: "25" },
  { name: "Miercoles", shortName: "Mié", date: "26" },
  { name: "Jueves", shortName: "Jue", date: "27" },
  { name: "Viernes", shortName: "Vie", date: "28" },
] as const;
